### ISSUE TITLE
Add some React

### ISSUE THREAD

**Issue by vishnut** [sweatshoptech/idb#31]
We need some React code
halp

**Comment by aaronmchang** [comment]
Next phase

**Comment by vishnut** [comment]
Add react somewhere, still required

**Comment by vishnut** [comment]
Maybe animate the tests, should be easy. Doesn't even have to be in real time. Just render.

**Comment by vishnut** [comment]
next phase, mentioned in report tools

**Comment by vishnut** [comment]
this phase?
