### ISSUE TITLE
Implement searching all attributes of all tables

### ISSUE THREAD

**Issue by vishnut** [sweatshoptech/idb#92]
Try Whoosh

- [x] The search must search every attribute of every model
- [x] The result of a search must be a list of links to crises and/or organizations and/or people (e.g. like Google).
- [x] The results must be contextualized and the search terms must show up and be highlighted.
- [x] The results must be clickable.
- [x] The results must be dense with at least 10 results per page.
- [x] The results must be paginated if there are more than 10 results.
- [x] Multi-word search must show clearly marked and results followed by or results.
- [x] All models must be searchable
- [x] Improve pagination, currently going to next pages goes to defaults to people

**Comment by vishnut** [comment]
Edited flask_whooshalchemyplus.py to match terms

**Comment by vishnut** [comment]
Whoosh has permissions issues
Also, http://whoosh.readthedocs.io/en/latest/searching.html#results-object

**Comment by vishnut** [comment]
Add tabs for other models, separate and from or results, card click-able,

**Comment by aaronmchang** [comment]
'OR' does not play well with 'LIKE' searches :weary: :100: :ok_hand: :fire:
